import type {
  Achievement,
  AirdropReadiness,
  DailyTask,
  FeaturedTask,
  TrendingCampaign,
  WalletActivityProfile,
  WeeklyMission,
} from '@web3-intelligence/shared';

export const SAMPLE_WALLET_PROFILE: WalletActivityProfile = {
  transactionCount: 42,
  bridgeActivity: false,
  lendingActivity: false,
  nftActivity: false,
  walletAgeDays: 45,
  dexActivity: true,
  governanceActivity: false,
  stakingActivity: false,
};

export const AIRDROP_READINESS: AirdropReadiness = {
  overallScore: 82,
  level: 'excellent',
  categoryBreakdown: [
    { category: 'bridge', label: 'Bridge', progress: 65 },
    { category: 'dex', label: 'DEX', progress: 88 },
    { category: 'lending', label: 'Lending', progress: 42 },
    { category: 'nft', label: 'NFT', progress: 55 },
    { category: 'governance', label: 'Governance', progress: 18 },
    { category: 'staking', label: 'Staking', progress: 72 },
    { category: 'social', label: 'Social', progress: 35 },
  ],
};

export const FEATURED_TASKS: FeaturedTask[] = [
  {
    id: 'bridge-across-base',
    title: 'Bridge Assets to Base',
    description: 'Bridge ETH from Ethereum to Base using Across Protocol.',
    protocol: 'Across',
    blockchain: 'Ethereum → Base',
    category: 'bridge',
    difficulty: 'easy',
    estimatedTime: '5–10 minutes',
    estimatedEligibilityBoost: 8,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+8 Eligibility Score',
    icon: '🌉',
    tags: ['L2', 'Base', 'Cross-chain'],
    ctaLabel: 'View Guide',
    secondaryCtaLabel: 'Learn More',
    guideUrl: '/airdrop',
    createdAt: '2026-07-28',
  },
  {
    id: 'bridge-stargate-arb',
    title: 'Bridge via Stargate',
    description: 'Move USDC between Ethereum and Arbitrum with Stargate.',
    protocol: 'Stargate',
    blockchain: 'Ethereum → Arbitrum',
    category: 'bridge',
    difficulty: 'easy',
    estimatedTime: '5–15 minutes',
    estimatedEligibilityBoost: 7,
    status: 'in_progress',
    progress: 40,
    rewardBadge: '+7 Eligibility Score',
    icon: '🛸',
    tags: ['USDC', 'LayerZero', 'Arbitrum'],
    ctaLabel: 'Continue',
    secondaryCtaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-25',
  },
  {
    id: 'bridge-layerzero-multi',
    title: 'Multi-Chain LayerZero Bridge',
    description: 'Bridge assets across 3+ chains using LayerZero endpoints.',
    protocol: 'LayerZero',
    blockchain: 'Multi-chain',
    category: 'bridge',
    difficulty: 'medium',
    estimatedTime: '20–30 minutes',
    estimatedEligibilityBoost: 12,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+12 Eligibility Score',
    icon: '🔗',
    tags: ['Omnichain', 'High reward'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    isNew: true,
    createdAt: '2026-07-29',
  },
  {
    id: 'bridge-relay-optimism',
    title: 'Relay Bridge to Optimism',
    description: 'Use Relay for fast, low-cost bridging to Optimism.',
    protocol: 'Relay',
    blockchain: 'Ethereum → Optimism',
    category: 'bridge',
    difficulty: 'easy',
    estimatedTime: '3–8 minutes',
    estimatedEligibilityBoost: 6,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+6 Eligibility Score',
    icon: '⚡',
    tags: ['Fast', 'Optimism'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-20',
  },
  {
    id: 'dex-uniswap-swap',
    title: 'Swap on Uniswap',
    description: 'Execute a swap on Uniswap V3 across any supported chain.',
    protocol: 'Uniswap',
    blockchain: 'Ethereum',
    category: 'dex',
    difficulty: 'easy',
    estimatedTime: '2–5 minutes',
    estimatedEligibilityBoost: 5,
    status: 'completed',
    progress: 100,
    rewardBadge: '+5 Eligibility Score',
    icon: '🦄',
    tags: ['Swap', 'DeFi'],
    ctaLabel: 'Completed',
    guideUrl: '/airdrop',
    createdAt: '2026-07-15',
  },
  {
    id: 'dex-aerodrome-base',
    title: 'Trade on Aerodrome',
    description: 'Swap tokens on Aerodrome, Base\'s leading DEX.',
    protocol: 'Aerodrome',
    blockchain: 'Base',
    category: 'dex',
    difficulty: 'easy',
    estimatedTime: '3–7 minutes',
    estimatedEligibilityBoost: 7,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+7 Eligibility Score',
    icon: '✈️',
    tags: ['Base', 've(3,3)'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    isNew: true,
    createdAt: '2026-07-30',
  },
  {
    id: 'dex-sushi-arbitrum',
    title: 'Swap on SushiSwap',
    description: 'Perform a swap on SushiSwap Arbitrum deployment.',
    protocol: 'SushiSwap',
    blockchain: 'Arbitrum',
    category: 'dex',
    difficulty: 'easy',
    estimatedTime: '2–5 minutes',
    estimatedEligibilityBoost: 4,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+4 Eligibility Score',
    icon: '🍣',
    tags: ['Arbitrum', 'Swap'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-18',
  },
  {
    id: 'dex-pancake-bnb',
    title: 'Trade on PancakeSwap',
    description: 'Swap BEP-20 tokens on PancakeSwap v3.',
    protocol: 'PancakeSwap',
    blockchain: 'BNB Chain',
    category: 'dex',
    difficulty: 'easy',
    estimatedTime: '3–6 minutes',
    estimatedEligibilityBoost: 5,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+5 Eligibility Score',
    icon: '🥞',
    tags: ['BNB', 'BSC'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-12',
  },
  {
    id: 'lending-aave-supply',
    title: 'Supply to Aave',
    description: 'Deposit USDC or ETH into Aave V3 lending pool.',
    protocol: 'Aave',
    blockchain: 'Ethereum',
    category: 'lending',
    difficulty: 'medium',
    estimatedTime: '10–15 minutes',
    estimatedEligibilityBoost: 10,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+10 Eligibility Score',
    icon: '👻',
    tags: ['DeFi', 'Yield'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-22',
  },
  {
    id: 'lending-compound',
    title: 'Lend on Compound',
    description: 'Supply assets to Compound III on Base or Ethereum.',
    protocol: 'Compound',
    blockchain: 'Base',
    category: 'lending',
    difficulty: 'medium',
    estimatedTime: '10–20 minutes',
    estimatedEligibilityBoost: 9,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+9 Eligibility Score',
    icon: '🏛️',
    tags: ['Lending', 'Base'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-19',
  },
  {
    id: 'lending-morpho',
    title: 'Deposit into Morpho',
    description: 'Use Morpho vaults for optimized lending yields.',
    protocol: 'Morpho',
    blockchain: 'Ethereum',
    category: 'lending',
    difficulty: 'medium',
    estimatedTime: '15–20 minutes',
    estimatedEligibilityBoost: 11,
    status: 'in_progress',
    progress: 25,
    rewardBadge: '+11 Eligibility Score',
    icon: '🦋',
    tags: ['Vaults', 'Optimized'],
    ctaLabel: 'Continue',
    secondaryCtaLabel: 'View Guide',
    guideUrl: '/airdrop',
    isNew: true,
    createdAt: '2026-07-27',
  },
  {
    id: 'nft-mint-zora',
    title: 'Mint NFT on Zora',
    description: 'Create or mint an NFT edition on Zora network.',
    protocol: 'Zora',
    blockchain: 'Base',
    category: 'nft',
    difficulty: 'easy',
    estimatedTime: '5–10 minutes',
    estimatedEligibilityBoost: 6,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+6 Eligibility Score',
    icon: '🎨',
    tags: ['Creator', 'Mint'],
    ctaLabel: 'View Guide',
    guideUrl: '/nfts',
    createdAt: '2026-07-21',
  },
  {
    id: 'nft-trade-opensea',
    title: 'Trade NFT on OpenSea',
    description: 'Buy or sell an NFT on OpenSea marketplace.',
    protocol: 'OpenSea',
    blockchain: 'Ethereum',
    category: 'nft',
    difficulty: 'easy',
    estimatedTime: '5–15 minutes',
    estimatedEligibilityBoost: 5,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+5 Eligibility Score',
    icon: '🌊',
    tags: ['Marketplace', 'Trade'],
    ctaLabel: 'View Guide',
    guideUrl: '/nfts',
    createdAt: '2026-07-16',
  },
  {
    id: 'nft-mint-farcaster',
    title: 'Mint Farcaster Frame NFT',
    description: 'Interact with and mint from a Farcaster Frame.',
    protocol: 'Farcaster',
    blockchain: 'Base',
    category: 'nft',
    difficulty: 'medium',
    estimatedTime: '10–15 minutes',
    estimatedEligibilityBoost: 8,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+8 Eligibility Score',
    icon: '🖼️',
    tags: ['Social', 'Frames'],
    ctaLabel: 'View Guide',
    guideUrl: '/nfts',
    isNew: true,
    createdAt: '2026-07-29',
  },
  {
    id: 'gov-snapshot-vote',
    title: 'Vote on Snapshot',
    description: 'Cast a governance vote on an active Snapshot proposal.',
    protocol: 'Snapshot',
    blockchain: 'Multi-chain',
    category: 'governance',
    difficulty: 'easy',
    estimatedTime: '3–5 minutes',
    estimatedEligibilityBoost: 7,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+7 Eligibility Score',
    icon: '🗳️',
    tags: ['DAO', 'Vote'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-14',
  },
  {
    id: 'gov-arbitrum-dao',
    title: 'Participate in Arbitrum DAO',
    description: 'Delegate or vote on Arbitrum governance proposals.',
    protocol: 'Arbitrum DAO',
    blockchain: 'Arbitrum',
    category: 'governance',
    difficulty: 'medium',
    estimatedTime: '10–20 minutes',
    estimatedEligibilityBoost: 9,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+9 Eligibility Score',
    icon: '🏗️',
    tags: ['L2', 'Delegation'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-11',
  },
  {
    id: 'gov-optimism-collective',
    title: 'Join Optimism Collective',
    description: 'Participate in Optimism governance and attestations.',
    protocol: 'Optimism',
    blockchain: 'Optimism',
    category: 'governance',
    difficulty: 'medium',
    estimatedTime: '15–25 minutes',
    estimatedEligibilityBoost: 10,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+10 Eligibility Score',
    icon: '🔴',
    tags: ['OP', 'RetroPGF'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-10',
  },
  {
    id: 'stake-eth-lido',
    title: 'Stake ETH with Lido',
    description: 'Stake ETH and receive stETH for liquid staking rewards.',
    protocol: 'Lido',
    blockchain: 'Ethereum',
    category: 'staking',
    difficulty: 'easy',
    estimatedTime: '5–10 minutes',
    estimatedEligibilityBoost: 8,
    status: 'completed',
    progress: 100,
    rewardBadge: '+8 Eligibility Score',
    icon: '🌊',
    tags: ['Liquid staking', 'stETH'],
    ctaLabel: 'Completed',
    guideUrl: '/airdrop',
    createdAt: '2026-07-08',
  },
  {
    id: 'stake-restake-eigen',
    title: 'Restake with EigenLayer',
    description: 'Restake stETH or other LSTs via EigenLayer.',
    protocol: 'EigenLayer',
    blockchain: 'Ethereum',
    category: 'staking',
    difficulty: 'hard',
    estimatedTime: '20–30 minutes',
    estimatedEligibilityBoost: 14,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+14 Eligibility Score',
    icon: '♾️',
    tags: ['Restaking', 'AVS'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    isNew: true,
    createdAt: '2026-07-28',
  },
  {
    id: 'stake-rocket-pool',
    title: 'Stake via Rocket Pool',
    description: 'Stake ETH through decentralized Rocket Pool validators.',
    protocol: 'Rocket Pool',
    blockchain: 'Ethereum',
    category: 'staking',
    difficulty: 'medium',
    estimatedTime: '10–15 minutes',
    estimatedEligibilityBoost: 9,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+9 Eligibility Score',
    icon: '🚀',
    tags: ['rETH', 'Decentralized'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-17',
  },
  {
    id: 'social-discord-join',
    title: 'Join Protocol Discord',
    description: 'Join official Discord servers for 3+ target protocols.',
    protocol: 'Discord',
    blockchain: 'Off-chain',
    category: 'social',
    difficulty: 'easy',
    estimatedTime: '5–10 minutes',
    estimatedEligibilityBoost: 3,
    status: 'in_progress',
    progress: 66,
    rewardBadge: '+3 Eligibility Score',
    icon: '💬',
    tags: ['Community', 'Social'],
    ctaLabel: 'Continue',
    guideUrl: '/airdrop',
    createdAt: '2026-07-13',
  },
  {
    id: 'social-follow-x',
    title: 'Follow Protocols on X',
    description: 'Follow official X accounts of potential airdrop projects.',
    protocol: 'X (Twitter)',
    blockchain: 'Off-chain',
    category: 'social',
    difficulty: 'easy',
    estimatedTime: '2–5 minutes',
    estimatedEligibilityBoost: 2,
    status: 'completed',
    progress: 100,
    rewardBadge: '+2 Eligibility Score',
    icon: '𝕏',
    tags: ['Social', 'Updates'],
    ctaLabel: 'Completed',
    guideUrl: '/airdrop',
    createdAt: '2026-07-09',
  },
  {
    id: 'social-galxe-quest',
    title: 'Complete Galxe Quest',
    description: 'Finish a Galxe campaign quest for an active protocol.',
    protocol: 'Galxe',
    blockchain: 'Multi-chain',
    category: 'social',
    difficulty: 'easy',
    estimatedTime: '10–20 minutes',
    estimatedEligibilityBoost: 6,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+6 Eligibility Score',
    icon: '🌌',
    tags: ['Quest', 'Campaign'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    isNew: true,
    createdAt: '2026-07-30',
  },
  {
    id: 'social-zealy-mission',
    title: 'Complete Zealy Mission',
    description: 'Earn XP by completing Zealy community missions.',
    protocol: 'Zealy',
    blockchain: 'Off-chain',
    category: 'social',
    difficulty: 'easy',
    estimatedTime: '15–30 minutes',
    estimatedEligibilityBoost: 5,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+5 Eligibility Score',
    icon: '🏅',
    tags: ['XP', 'Community'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-24',
  },
  {
    id: 'bridge-hop-polygon',
    title: 'Bridge to Polygon via Hop',
    description: 'Use Hop Protocol to bridge assets to Polygon.',
    protocol: 'Hop Protocol',
    blockchain: 'Ethereum → Polygon',
    category: 'bridge',
    difficulty: 'easy',
    estimatedTime: '5–12 minutes',
    estimatedEligibilityBoost: 6,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+6 Eligibility Score',
    icon: '🐸',
    tags: ['Polygon', 'L2'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-23',
  },
  {
    id: 'dex-curve-swap',
    title: 'Swap on Curve Finance',
    description: 'Exchange stablecoins on Curve for low slippage.',
    protocol: 'Curve',
    blockchain: 'Ethereum',
    category: 'dex',
    difficulty: 'medium',
    estimatedTime: '5–10 minutes',
    estimatedEligibilityBoost: 6,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+6 Eligibility Score',
    icon: '📈',
    tags: ['Stableswap', 'DeFi'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-07',
  },
  {
    id: 'dex-balancer-pool',
    title: 'Swap on Balancer',
    description: 'Execute a weighted pool swap on Balancer V2.',
    protocol: 'Balancer',
    blockchain: 'Ethereum',
    category: 'dex',
    difficulty: 'medium',
    estimatedTime: '5–10 minutes',
    estimatedEligibilityBoost: 5,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+5 Eligibility Score',
    icon: '⚖️',
    tags: ['Pools', 'Weighted'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-06',
  },
  {
    id: 'lending-spark',
    title: 'Supply to Spark Protocol',
    description: 'Deposit DAI into Spark lending on Ethereum.',
    protocol: 'Spark',
    blockchain: 'Ethereum',
    category: 'lending',
    difficulty: 'medium',
    estimatedTime: '10–15 minutes',
    estimatedEligibilityBoost: 8,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+8 Eligibility Score',
    icon: '✨',
    tags: ['Maker', 'DAI'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-05',
  },
  {
    id: 'nft-mirror-publish',
    title: 'Publish on Mirror',
    description: 'Mint a writing NFT or entry on Mirror.xyz.',
    protocol: 'Mirror',
    blockchain: 'Ethereum',
    category: 'nft',
    difficulty: 'medium',
    estimatedTime: '15–25 minutes',
    estimatedEligibilityBoost: 7,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+7 Eligibility Score',
    icon: '📝',
    tags: ['Writing', 'Creator'],
    ctaLabel: 'View Guide',
    guideUrl: '/nfts',
    createdAt: '2026-07-04',
  },
  {
    id: 'gov-tally-delegate',
    title: 'Delegate on Tally',
    description: 'Delegate voting power via Tally for an active DAO.',
    protocol: 'Tally',
    blockchain: 'Ethereum',
    category: 'governance',
    difficulty: 'easy',
    estimatedTime: '5–10 minutes',
    estimatedEligibilityBoost: 6,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+6 Eligibility Score',
    icon: '📊',
    tags: ['Delegation', 'DAO'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-03',
  },
  {
    id: 'stake-matic-polygon',
    title: 'Stake MATIC on Polygon',
    description: 'Delegate MATIC to a validator on Polygon network.',
    protocol: 'Polygon Staking',
    blockchain: 'Polygon',
    category: 'staking',
    difficulty: 'easy',
    estimatedTime: '5–10 minutes',
    estimatedEligibilityBoost: 5,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+5 Eligibility Score',
    icon: '💜',
    tags: ['MATIC', 'Validator'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-02',
  },
  {
    id: 'bridge-wormhole',
    title: 'Bridge with Wormhole',
    description: 'Transfer tokens cross-chain using Wormhole portal.',
    protocol: 'Wormhole',
    blockchain: 'Multi-chain',
    category: 'bridge',
    difficulty: 'medium',
    estimatedTime: '10–20 minutes',
    estimatedEligibilityBoost: 9,
    status: 'not_started',
    progress: 0,
    rewardBadge: '+9 Eligibility Score',
    icon: '🌀',
    tags: ['Portal', 'Cross-chain'],
    ctaLabel: 'View Guide',
    guideUrl: '/airdrop',
    createdAt: '2026-07-01',
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-bridge',
    title: 'First Bridge',
    description: 'Complete your first cross-chain bridge transaction.',
    icon: '🌉',
    status: 'unlocked',
    progress: 1,
    maxProgress: 1,
    unlockedAt: '2026-06-15',
    category: 'bridge',
  },
  {
    id: 'defi-explorer',
    title: 'DeFi Explorer',
    description: 'Interact with 5 different DeFi protocols.',
    icon: '🧭',
    status: 'in_progress',
    progress: 3,
    maxProgress: 5,
    category: 'dex',
  },
  {
    id: 'nft-collector',
    title: 'NFT Collector',
    description: 'Hold NFTs from 3 different collections.',
    icon: '🖼️',
    status: 'locked',
    progress: 0,
    maxProgress: 3,
    category: 'nft',
  },
  {
    id: 'governance-voter',
    title: 'Governance Voter',
    description: 'Cast votes on 3 governance proposals.',
    icon: '🗳️',
    status: 'locked',
    progress: 0,
    maxProgress: 3,
    category: 'governance',
  },
  {
    id: 'multi-chain-user',
    title: 'Multi-chain User',
    description: 'Have active transactions on 4+ blockchains.',
    icon: '🌍',
    status: 'in_progress',
    progress: 2,
    maxProgress: 4,
    category: 'bridge',
  },
  {
    id: 'power-wallet',
    title: 'Power Wallet',
    description: 'Reach an airdrop readiness score of 90+.',
    icon: '⚡',
    status: 'in_progress',
    progress: 82,
    maxProgress: 90,
    category: 'general',
  },
  {
    id: 'swap-master',
    title: 'Swap Master',
    description: 'Complete 10 DEX swap transactions.',
    icon: '🔄',
    status: 'in_progress',
    progress: 6,
    maxProgress: 10,
    category: 'dex',
  },
  {
    id: 'lending-lord',
    title: 'Lending Lord',
    description: 'Supply assets to 2 lending protocols.',
    icon: '🏦',
    status: 'locked',
    progress: 0,
    maxProgress: 2,
    category: 'lending',
  },
  {
    id: 'social-butterfly',
    title: 'Social Butterfly',
    description: 'Complete 5 social/community tasks.',
    icon: '🦋',
    status: 'in_progress',
    progress: 2,
    maxProgress: 5,
    category: 'social',
  },
  {
    id: 'stake-holder',
    title: 'Stake Holder',
    description: 'Stake assets on 2 different staking platforms.',
    icon: '🔒',
    status: 'in_progress',
    progress: 1,
    maxProgress: 2,
    category: 'staking',
  },
  {
    id: 'early-adopter',
    title: 'Early Adopter',
    description: 'Complete a task within 24 hours of it being featured.',
    icon: '🚀',
    status: 'unlocked',
    progress: 1,
    maxProgress: 1,
    unlockedAt: '2026-07-20',
    category: 'general',
  },
  {
    id: 'bridge-hopper',
    title: 'Bridge Hopper',
    description: 'Bridge assets to 3 different L2 networks.',
    icon: '🦘',
    status: 'locked',
    progress: 1,
    maxProgress: 3,
    category: 'bridge',
  },
  {
    id: 'dao-citizen',
    title: 'DAO Citizen',
    description: 'Participate in governance on 2 different DAOs.',
    icon: '🏛️',
    status: 'locked',
    progress: 0,
    maxProgress: 2,
    category: 'governance',
  },
  {
    id: 'yield-farmer',
    title: 'Yield Farmer',
    description: 'Earn yield from lending and staking combined.',
    icon: '🌾',
    status: 'in_progress',
    progress: 1,
    maxProgress: 2,
    category: 'lending',
  },
  {
    id: 'quest-champion',
    title: 'Quest Champion',
    description: 'Complete 3 Galxe or Zealy quest campaigns.',
    icon: '🏆',
    status: 'locked',
    progress: 0,
    maxProgress: 3,
    category: 'social',
  },
  {
    id: 'restake-pioneer',
    title: 'Restake Pioneer',
    description: 'Restake assets via EigenLayer or similar protocol.',
    icon: '♾️',
    status: 'locked',
    progress: 0,
    maxProgress: 1,
    category: 'staking',
  },
  {
    id: 'creator-mint',
    title: 'Creator Mint',
    description: 'Mint an original NFT on any creator platform.',
    icon: '🎨',
    status: 'locked',
    progress: 0,
    maxProgress: 1,
    category: 'nft',
  },
  {
    id: 'weekly-warrior',
    title: 'Weekly Warrior',
    description: 'Complete all weekly missions in a single week.',
    icon: '🗡️',
    status: 'locked',
    progress: 0,
    maxProgress: 1,
    category: 'general',
  },
  {
    id: 'daily-grinder',
    title: 'Daily Grinder',
    description: 'Complete daily tasks for 7 consecutive days.',
    icon: '📅',
    status: 'in_progress',
    progress: 4,
    maxProgress: 7,
    category: 'general',
  },
  {
    id: 'protocol-diversifier',
    title: 'Protocol Diversifier',
    description: 'Use protocols from all 7 task categories.',
    icon: '🎯',
    status: 'in_progress',
    progress: 4,
    maxProgress: 7,
    category: 'general',
  },
];

export const DAILY_TASK_POOL: DailyTask[] = [
  {
    id: 'daily-swap',
    title: 'Swap once',
    description: 'Execute one DEX swap on any supported chain.',
    category: 'dex',
    reward: '+2 Score',
    progress: 0,
    target: 1,
    completed: false,
  },
  {
    id: 'daily-bridge',
    title: 'Bridge once',
    description: 'Complete one cross-chain bridge transaction.',
    category: 'bridge',
    reward: '+3 Score',
    progress: 0,
    target: 1,
    completed: false,
  },
  {
    id: 'daily-vote',
    title: 'Vote once',
    description: 'Cast a governance vote on any active proposal.',
    category: 'governance',
    reward: '+2 Score',
    progress: 0,
    target: 1,
    completed: false,
  },
  {
    id: 'daily-mint',
    title: 'Mint NFT',
    description: 'Mint or collect one NFT today.',
    category: 'nft',
    reward: '+2 Score',
    progress: 0,
    target: 1,
    completed: false,
  },
  {
    id: 'daily-protocols',
    title: 'Interact with 2 protocols',
    description: 'Use two different DeFi protocols in one day.',
    category: 'dex',
    reward: '+4 Score',
    progress: 1,
    target: 2,
    completed: false,
  },
  {
    id: 'daily-stake',
    title: 'Stake assets',
    description: 'Stake or restake any supported asset.',
    category: 'staking',
    reward: '+3 Score',
    progress: 0,
    target: 1,
    completed: false,
  },
  {
    id: 'daily-lend',
    title: 'Supply to lending',
    description: 'Deposit assets into a lending protocol.',
    category: 'lending',
    reward: '+3 Score',
    progress: 0,
    target: 1,
    completed: false,
  },
  {
    id: 'daily-social',
    title: 'Complete social quest',
    description: 'Finish one Galxe or Zealy quest task.',
    category: 'social',
    reward: '+2 Score',
    progress: 0,
    target: 1,
    completed: false,
  },
  {
    id: 'daily-check-wallet',
    title: 'Check eligibility',
    description: 'Review your airdrop eligibility score.',
    category: 'general',
    reward: '+1 Score',
    progress: 1,
    target: 1,
    completed: true,
  },
  {
    id: 'daily-gas-track',
    title: 'Track gas spend',
    description: 'Review your gas analytics for the week.',
    category: 'general',
    reward: '+1 Score',
    progress: 0,
    target: 1,
    completed: false,
  },
];

export const WEEKLY_MISSIONS: WeeklyMission[] = [
  {
    id: 'weekly-10-tx',
    title: '10 Transactions',
    description: 'Complete 10 on-chain transactions this week.',
    category: 'general',
    reward: '+15 Score',
    progress: 4,
    target: 10,
    deadline: '2026-08-03',
    completed: false,
  },
  {
    id: 'weekly-5-protocols',
    title: '5 Protocols',
    description: 'Interact with 5 different protocols this week.',
    category: 'general',
    reward: '+12 Score',
    progress: 2,
    target: 5,
    deadline: '2026-08-03',
    completed: false,
  },
  {
    id: 'weekly-bridge-3-chains',
    title: 'Bridge 3 Chains',
    description: 'Bridge assets to 3 different chains.',
    category: 'bridge',
    reward: '+18 Score',
    progress: 0,
    target: 3,
    deadline: '2026-08-03',
    completed: false,
  },
  {
    id: 'weekly-lending',
    title: 'Use Lending',
    description: 'Supply assets to any lending protocol.',
    category: 'lending',
    reward: '+10 Score',
    progress: 0,
    target: 1,
    deadline: '2026-08-03',
    completed: false,
  },
  {
    id: 'weekly-stake',
    title: 'Stake Assets',
    description: 'Stake or restake assets this week.',
    category: 'staking',
    reward: '+10 Score',
    progress: 1,
    target: 1,
    deadline: '2026-08-03',
    completed: true,
  },
  {
    id: 'weekly-governance',
    title: 'Governance Week',
    description: 'Vote on 2 governance proposals.',
    category: 'governance',
    reward: '+8 Score',
    progress: 0,
    target: 2,
    deadline: '2026-08-03',
    completed: false,
  },
  {
    id: 'weekly-nft',
    title: 'NFT Activity',
    description: 'Mint or trade 2 NFTs this week.',
    category: 'nft',
    reward: '+8 Score',
    progress: 0,
    target: 2,
    deadline: '2026-08-03',
    completed: false,
  },
  {
    id: 'weekly-dex-volume',
    title: 'DEX Volume',
    description: 'Execute 5 swaps across any DEX.',
    category: 'dex',
    reward: '+10 Score',
    progress: 2,
    target: 5,
    deadline: '2026-08-03',
    completed: false,
  },
  {
    id: 'weekly-social',
    title: 'Community Builder',
    description: 'Complete 3 social/community tasks.',
    category: 'social',
    reward: '+6 Score',
    progress: 1,
    target: 3,
    deadline: '2026-08-03',
    completed: false,
  },
  {
    id: 'weekly-new-protocol',
    title: 'Try Something New',
    description: 'Use a protocol you haven\'t interacted with before.',
    category: 'general',
    reward: '+8 Score',
    progress: 0,
    target: 1,
    deadline: '2026-08-03',
    completed: false,
  },
];

export const TRENDING_CAMPAIGNS: TrendingCampaign[] = [
  {
    id: 'camp-zksync',
    project: 'zkSync Era',
    chain: 'zkSync',
    difficulty: 'medium',
    estimatedOpportunity: 'High',
    deadline: '2026-09-30',
    risk: 'low',
    popularity: 94,
    description: 'Sustained L2 activity and contract deployments may qualify for future rewards.',
    url: '/airdrop',
  },
  {
    id: 'camp-linea',
    project: 'Linea',
    chain: 'Linea',
    difficulty: 'easy',
    estimatedOpportunity: 'High',
    deadline: '2026-08-31',
    risk: 'low',
    popularity: 91,
    description: 'Consistent weekly interactions on Linea mainnet apps.',
    url: '/airdrop',
  },
  {
    id: 'camp-scroll',
    project: 'Scroll',
    chain: 'Scroll',
    difficulty: 'medium',
    estimatedOpportunity: 'Medium',
    deadline: '2026-10-15',
    risk: 'low',
    popularity: 87,
    description: 'Bridge, swap, and lend on Scroll ecosystem protocols.',
    url: '/airdrop',
  },
  {
    id: 'camp-base-eco',
    project: 'Base Ecosystem',
    chain: 'Base',
    difficulty: 'easy',
    estimatedOpportunity: 'Medium',
    risk: 'low',
    popularity: 89,
    description: 'Onchain summer campaigns and Base-native app usage.',
    url: '/airdrop',
  },
  {
    id: 'camp-eigenlayer',
    project: 'EigenLayer',
    chain: 'Ethereum',
    difficulty: 'hard',
    estimatedOpportunity: 'High',
    deadline: '2026-12-31',
    risk: 'medium',
    popularity: 85,
    description: 'Restaking activity and AVS participation.',
    url: '/airdrop',
  },
  {
    id: 'camp-layerzero',
    project: 'LayerZero',
    chain: 'Multi-chain',
    difficulty: 'medium',
    estimatedOpportunity: 'High',
    risk: 'low',
    popularity: 92,
    description: 'Omnichain messaging and bridge volume across endpoints.',
    url: '/airdrop',
  },
  {
    id: 'camp-paradigm-l2',
    project: 'Blast',
    chain: 'Blast',
    difficulty: 'easy',
    estimatedOpportunity: 'Medium',
    deadline: '2026-08-15',
    risk: 'medium',
    popularity: 78,
    description: 'Native yield and Blast-native dApp interactions.',
    url: '/airdrop',
  },
  {
    id: 'camp-celestia',
    project: 'Celestia',
    chain: 'Celestia',
    difficulty: 'medium',
    estimatedOpportunity: 'Medium',
    risk: 'low',
    popularity: 72,
    description: 'Modular data availability and rollup deployments.',
    url: '/airdrop',
  },
  {
    id: 'camp-farcaster',
    project: 'Farcaster',
    chain: 'Optimism',
    difficulty: 'easy',
    estimatedOpportunity: 'Watchlist',
    risk: 'low',
    popularity: 80,
    description: 'Social graph activity and Frame interactions.',
    url: '/airdrop',
  },
  {
    id: 'camp-berachain',
    project: 'Berachain',
    chain: 'Berachain',
    difficulty: 'medium',
    estimatedOpportunity: 'High',
    deadline: '2026-09-01',
    risk: 'medium',
    popularity: 88,
    description: 'Testnet and mainnet DeFi interactions on Berachain.',
    url: '/airdrop',
  },
  {
    id: 'camp-monad',
    project: 'Monad',
    chain: 'Monad',
    difficulty: 'easy',
    estimatedOpportunity: 'Watchlist',
    risk: 'low',
    popularity: 76,
    description: 'Early testnet participation and developer activity.',
    url: '/airdrop',
  },
  {
    id: 'camp-sui',
    project: 'Sui Ecosystem',
    chain: 'Sui',
    difficulty: 'medium',
    estimatedOpportunity: 'Medium',
    risk: 'low',
    popularity: 70,
    description: 'Move-based DeFi and NFT activity on Sui.',
    url: '/airdrop',
  },
  {
    id: 'camp-aptos',
    project: 'Aptos DeFi',
    chain: 'Aptos',
    difficulty: 'medium',
    estimatedOpportunity: 'Medium',
    risk: 'low',
    popularity: 68,
    description: 'Swap, lend, and stake on Aptos protocols.',
    url: '/airdrop',
  },
  {
    id: 'camp-starknet',
    project: 'Starknet',
    chain: 'Starknet',
    difficulty: 'hard',
    estimatedOpportunity: 'High',
    deadline: '2026-11-30',
    risk: 'medium',
    popularity: 83,
    description: 'Cairo contract interactions and Starknet DeFi.',
    url: '/airdrop',
  },
  {
    id: 'camp-mode',
    project: 'Mode Network',
    chain: 'Mode',
    difficulty: 'easy',
    estimatedOpportunity: 'Medium',
    deadline: '2026-08-20',
    risk: 'low',
    popularity: 74,
    description: 'OP Stack L2 with sequencer revenue sharing model.',
    url: '/airdrop',
  },
];
